// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: event.proto

package eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChangeEvent mirrors cdc.ChangeEvent on the wire.
type ChangeEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SourceId string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Schema   string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Table    string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	// op is c (create), u (update), d (delete), r (snapshot read) or t (truncate).
	Op            string                 `protobuf:"bytes,4,opt,name=op,proto3" json:"op,omitempty"`
	Before        *structpb.Struct       `protobuf:"bytes,5,opt,name=before,proto3" json:"before,omitempty"`
	After         *structpb.Struct       `protobuf:"bytes,6,opt,name=after,proto3" json:"after,omitempty"`
	Position      string                 `protobuf:"bytes,7,opt,name=position,proto3" json:"position,omitempty"`
	CommitTs      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=commit_ts,json=commitTs,proto3" json:"commit_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEvent) Reset() {
	*x = ChangeEvent{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEvent) ProtoMessage() {}

func (x *ChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEvent.ProtoReflect.Descriptor instead.
func (*ChangeEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ChangeEvent) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *ChangeEvent) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ChangeEvent) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *ChangeEvent) GetBefore() *structpb.Struct {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *ChangeEvent) GetAfter() *structpb.Struct {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *ChangeEvent) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *ChangeEvent) GetCommitTs() *timestamppb.Timestamp {
	if x != nil {
		return x.CommitTs
	}
	return nil
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\rslipstream.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x02\n" +
	"\vChangeEvent\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\x12\x0e\n" +
	"\x02op\x18\x04 \x01(\tR\x02op\x12/\n" +
	"\x06before\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06before\x12-\n" +
	"\x05after\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x05after\x12\x1a\n" +
	"\bposition\x18\a \x01(\tR\bposition\x127\n" +
	"\tcommit_ts\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bcommitTsB7Z5github.com/aupv9/slipstream/internal/encoding/eventpbb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_event_proto_goTypes = []any{
	(*ChangeEvent)(nil),           // 0: slipstream.v1.ChangeEvent
	(*structpb.Struct)(nil),       // 1: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_event_proto_depIdxs = []int32{
	1, // 0: slipstream.v1.ChangeEvent.before:type_name -> google.protobuf.Struct
	1, // 1: slipstream.v1.ChangeEvent.after:type_name -> google.protobuf.Struct
	2, // 2: slipstream.v1.ChangeEvent.commit_ts:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
